export const SET_ACTIVATION_PENDING = "SET_ACTIVATION_PENDING";
export const SET_ACTIVATION_SUCCESS = "SET_ACTIVATION_SUCCESS";
export const SET_ACTIVATION_ERROR = "SET_ACTIVATION_ERROR";

export const SET_DELETE_ACCOUNT_PENDING = "SET_DELETE_ACCOUNT_PENDING";
export const SET_DELETE_ACCOUNT_ERROR = "SET_DELETE_ACCOUNT_ERROR";

export const SET_EMAIL_PENDING = "SET_EMAIL_PENDING";
export const SET_EMAIL_SUCCESS = "SET_EMAIL_SUCCESS";
export const SET_EMAIL_ERROR = "SET_EMAIL_ERROR";

export const SET_FORGOT_PASSWORD_PENDING = "SET_FORGOT_PASSWORD_PENDING";
export const SET_FORGOT_PASSWORD_SUCCESS = "SET_FORGOT_PASSWORD_SUCCESS";
export const SET_FORGOT_PASSWORD_ERROR = "SET_FORGOT_PASSWORD_ERROR";

export const SET_LOGIN_PENDING = "SET_LOGIN_PENDING";
export const SET_LOGIN_SUCCESS = "SET_LOGIN_SUCCESS";
export const SET_LOGIN_MESSAGE_PRINTED = "SET_LOGIN_MESSAGE_PRINTED";
export const SET_LOGIN_ERROR = "SET_LOGIN_ERROR";

export const SET_LOGOUT_PENDING = "SET_LOGOUT_PENDING";
export const SET_LOGOUT_SUCCESS = "SET_LOGOUT_SUCCESS";
export const SET_LOGOUT_MESSAGE_PRINTED = "SET_LOGOUT_MESSAGE_PRINTED";

export const SET_PASSWORD_PENDING = "SET_PASSWORD_PENDING";
export const SET_PASSWORD_SUCCESS = "SET_PASSWORD_SUCCESS";
export const SET_PASSWORD_ERROR = "SET_PASSWORD_ERROR";

export const SET_PROFILE_LOADING = "SET_PROFILE_LOADING";
export const SET_PROFILE_LOADED = "SET_PROFILE_LOADED";
export const SET_PROFILE_UNLOADABLE = "SET_PROFILE_UNLOADABLE";

export const SET_PROFILE_PENDING = "SET_PROFILE_PENDING";
export const SET_PROFILE_SUCCESS = "SET_PROFILE_SUCCESS";
export const SET_PROFILE_MESSAGE_PRINTED = "SET_PROFILE_MESSAGE_PRINTED";
export const SET_PROFILE_ERROR = "SET_PROFILE_ERROR";

export const SET_REGISTER_PENDING = "SET_REGISTER_PENDING";
export const SET_REGISTER_SUCCESS = "SET_REGISTER_SUCCESS";
export const SET_REGISTER_ERROR = "SET_REGISTER_ERROR";
