export const SET_LOGIN_PENDING = "SET_LOGIN_PENDING";
export const SET_LOGIN_SUCCESS = "SET_LOGIN_SUCCESS";
export const SET_LOGIN_MESSAGE_PRINTED = "SET_LOGIN_MESSAGE_PRINTED";
export const SET_LOGIN_ERROR = "SET_LOGIN_ERROR";

export const SET_LOGOUT_PENDING = "SET_LOGOUT_PENDING";
export const SET_LOGOUT_SUCCESS = "SET_LOGOUT_SUCCESS";
export const SET_LOGOUT_MESSAGE_PRINTED = "SET_LOGOUT_MESSAGE_PRINTED";

export const SET_REGISTER_PENDING = "SET_REGISTER_PENDING";
export const SET_REGISTER_SUCCESS = "SET_REGISTER_SUCCESS";
export const SET_REGISTER_ERROR = "SET_REGISTER_ERROR";
