export const DOGS_BEGIN_CALL_ACTION = "DOGS_BEGIN_CALL_ACTION";
export const DOGS_CALL_ERROR = "DOGS_CALL_ERROR";
export const DOGS_LOAD_SUCCESS = "DOGS_LOAD_SUCCESS";

export const SET_LOGIN_PENDING = 'SET_LOGIN_PENDING';
export const SET_LOGIN_SUCCESS = 'SET_LOGIN_SUCCESS';
export const SET_LOGIN_ERROR = 'SET_LOGIN_ERROR';
